// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcNkVNWs2NglPW7OM0i1WYMLB-iuO9P8I',
    appId: '1:878376302317:web:6d9411d2aa8c4fb9713ee4',
    messagingSenderId: '878376302317',
    projectId: 'yuhouse-aeb37',
    authDomain: 'yuhouse-aeb37.firebaseapp.com',
    storageBucket: 'yuhouse-aeb37.appspot.com',
    measurementId: 'G-YB2QWTGRE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATBTR16HeP2Uw4oHOp7ESRauj2PJhgleY',
    appId: '1:878376302317:android:2e18a5f5a000dd4a713ee4',
    messagingSenderId: '878376302317',
    projectId: 'yuhouse-aeb37',
    storageBucket: 'yuhouse-aeb37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoN3f7lEAIAvw7sT3geDBHKRbCsv7zoaw',
    appId: '1:878376302317:ios:3deca1335b26eb18713ee4',
    messagingSenderId: '878376302317',
    projectId: 'yuhouse-aeb37',
    storageBucket: 'yuhouse-aeb37.appspot.com',
    iosBundleId: 'com.example.yuhouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoN3f7lEAIAvw7sT3geDBHKRbCsv7zoaw',
    appId: '1:878376302317:ios:3deca1335b26eb18713ee4',
    messagingSenderId: '878376302317',
    projectId: 'yuhouse-aeb37',
    storageBucket: 'yuhouse-aeb37.appspot.com',
    iosBundleId: 'com.example.yuhouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcNkVNWs2NglPW7OM0i1WYMLB-iuO9P8I',
    appId: '1:878376302317:web:2f82e3bcabf5d548713ee4',
    messagingSenderId: '878376302317',
    projectId: 'yuhouse-aeb37',
    authDomain: 'yuhouse-aeb37.firebaseapp.com',
    storageBucket: 'yuhouse-aeb37.appspot.com',
    measurementId: 'G-51FQZ17D5X',
  );
}
